# Generated by Django 5.2.11 on 2026-02-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LifeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('education', models.CharField(max_length=100)),
                ('career', models.CharField(max_length=100)),
                ('risk', models.FloatField()),
                ('probability', models.FloatField()),
                ('autobiography', models.TextField(default='')),
            ],
        ),
    ]
