# Generated by Django 5.2.11 on 2026-02-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifeprofile',
            name='risk',
        ),
        migrations.AlterField(
            model_name='lifeprofile',
            name='probability',
            field=models.FloatField(default=0.0),
        ),
    ]
