# Generated by Django 5.2.11 on 2026-02-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_profile', '0002_remove_lifeprofile_risk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lifeprofile',
            old_name='career',
            new_name='profession',
        ),
        migrations.RemoveField(
            model_name='lifeprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='lifeprofile',
            name='probability',
        ),
        migrations.AlterField(
            model_name='lifeprofile',
            name='autobiography',
            field=models.TextField(blank=True),
        ),
    ]
