# Generated by Django 5.2.11 on 2026-02-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_profile', '0003_rename_career_lifeprofile_profession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifeprofile',
            name='autobiography',
        ),
        migrations.AddField(
            model_name='lifeprofile',
            name='probability',
            field=models.IntegerField(default=0),
        ),
    ]
