# Generated by Django 5.2.11 on 2026-02-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_profile', '0004_remove_lifeprofile_autobiography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeprofile',
            name='probability',
            field=models.IntegerField(),
        ),
    ]
